/*
 * Copyright (c) 2024-2026. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause.
 */

#pragma once

#include "AND/Types.h"

namespace AND {

using Hash = u64;

NODISCARD ALWAYS_INLINE Hash get_hash(u64 const& value)
{
    // We use the SplitMix64 output-mixing finalizer for 64-bit values.
    // It provides strong avalanche/bit diffusion for hash-table use (non-cryptographic).
    // References:
    // - SplitMix64 overview/algorithm: https://rosettacode.org/wiki/Pseudo-random_numbers/Splitmix64
    // - Original SplitMix context: Steele/Lea/Flood (OOPSLA 2014): https://gee.cs.oswego.edu/dl/papers/oopsla14.pdf
    // NOTE: This function was generated by GPT-5.3 Codex so it might have vulnerabilities.

    Hash hash_value = value;
    hash_value ^= (hash_value >> 30);
    hash_value *= 0xBF58476D1CE4E5B9;
    hash_value ^= (hash_value >> 27);
    hash_value *= 0x94D049BB133111EB;
    hash_value ^= (hash_value >> 31);
    return hash_value;
}

#define AND_DECLARE_GET_HASH_FOR_INTEGER(type)    \
    NODISCARD ALWAYS_INLINE Hash get(type value)  \
    {                                             \
        return get_hash(static_cast<u64>(value)); \
    }

AND_DECLARE_GET_HASH_FOR_INTEGER(u8);
AND_DECLARE_GET_HASH_FOR_INTEGER(u16);
AND_DECLARE_GET_HASH_FOR_INTEGER(u32);

AND_DECLARE_GET_HASH_FOR_INTEGER(s8);
AND_DECLARE_GET_HASH_FOR_INTEGER(s16);
AND_DECLARE_GET_HASH_FOR_INTEGER(s32);
AND_DECLARE_GET_HASH_FOR_INTEGER(s64);

#undef AND_DECLARE_GET_HASH_FOR_INTEGER

} // namespace AND

#if AND_INCLUDE_IN_GLOBAL_NAMESPACE
using AND::get_hash;
using AND::Hash;
#endif
